---
title: "regression-numerical-linalg-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{regression-numerical-linalg-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

---
```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dev = 'pdf')
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(tidy=TRUE)
knitr::opts_chunk$set(prompt=FALSE)
knitr::opts_chunk$set(fig.height=5)
knitr::opts_chunk$set(fig.width=7)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=TRUE)
knitr::opts_knit$set(root.dir = ".")
```

```{r}
library(appregr)
```


```{r}
results <- appregr::getmodel('gala')
lm.fit <- results$fit
summary(lm.fit)
df <-results$data
x <- model.matrix( ~ Area + Elevation + Nearest + Scruz  + Adjacent,df)
y <- df$Species
xtxi <- solve(t(x) %*% x)
xtxi %*% t(x) %*% y
solve(crossprod(x,x),crossprod(x,y))
names(lm.fit)
lm.fitsum <- summary(lm.fit)
names(lm.fitsum)
sqrt(deviance(lm.fit)/df.residual(lm.fit))
lm.fitsum$sigma
xtxi <- lm.fitsum$cov.unscaled
sqrt(diag(xtxi))*60.975
lm.fitsum$coef[,2]
qrx <- qr(x)
dim(qr.Q(qrx))
(f <- t(qr.Q(qrx)) %*% y)
backsolve(qr.R(qrx),f)

df$Adiff <- df$Area -df$Adjacent
lm.fit <- lm(Species ~ Area+Elevation+Nearest+Scruz+Adjacent +Adiff,df)
summary(lm.fit)
set.seed(123)
Adiffe <- df$Adiff+0.001*(runif(30)-0.5)
lm.fit <- lm(Species ~ Area+Elevation+Nearest+Scruz +Adjacent+Adiffe,df)
summary(lm.fit)

# #
# data(odor, package="faraway")
# odor
# cov(odor[,-1])
# lm.fit <- lm(odor ~ temp + gas + pack, odor)
# summary(lm.fit,cor=T)
# lm.fit <- lm(odor ~ gas + pack, odor)
# summary(lm.fit)
# x <- 1:20
# y <- x+rnorm(20)
```
